language: php

sudo: required

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

install:
  - ./travis-install.sh
  - travis_retry composer install --no-interaction

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

script:
  - phpunit --no-coverage
